### ISSUE TITLE
Fix or remove invalid resolutions

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#857]
This would be more of a convenience feature, but it is for example possible to select the resolution 1366x768.
However, this crashes the game (in my case at least).

It would be practical if resolutions like this (if there are more) are either fixed, or simply removed from the menu.

**Comment by patel-nikhil** [comment]
1366x768 resolution works fine for my computer, as does 1360x768 - this likely depends on supported resolutions for your specific monitor. There's probably some Windows API for determining the set of supported resolutions that SHC uses internally (speculating), I wonder if it's compatibility mode or a similar behind-the-scenes setting that may be causing the crash rather than the game resolution itself

**Comment by TheRedDaemon** [comment]
Ok, I found the issue. It is called "kinda alpha status software". 🙃 
Back when I wrote this issue I forgot to validate if the "rendered screen to OpenGL display" feature I created for the UCP3 had anything to do with this. It has. 1366x768 works otherwise.
Submitted myself a bug for whenever I find the time to work on it again.

I close this for now.
