### ISSUE TITLE
Despawning Peasents

### ISSUE THREAD

**Issue by Euski** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#869]
Good Morning,

does anyone know about a problem, where Peasents are despawning directly after comming out of the keep? They start moving towards the fireplace, begin to schade away, as they would be transformed to a troop for example but just disapear. It unfortunatley accours right frequently to a AI of mine, rendering it nearly unable to recruit. It seems as well, that those disapearing Peasents add to the Population somehow, because later in the Game (I build a ton of Houses hoping to fix it) Peasents stop comming completly

Thanks in advance
Euski

**Comment by Russianstory** [comment]
Most likely this is a banal population limit. Limiting the number of units in the game (on the map) I have encountered this many times. It cannot be fixed. At least by our comrades from UCP. This is exactly the level of the game developers. It seems to me

**Comment by Euski** [comment]
Thanks for your fast reply. 
Unfortunatley ist neither troop Limit or Objekt Limit.
The enemy AI ist funtioning fine at the Same time and ist Sometimes occurs already at about 300 Troops e.g. in 1 vs 1

**Comment by Russianstory** [comment]
do not mention it. But wait ... after a while the guys will also answer. I think they have something to say. Check your topic periodically, bro.

**Comment by GRhin** [comment]
I believe this is an error with your AIC settings. I am not sure the exact situation that causes this, so someone who knows more about AIC can answer clearer, faster response can be found on the discord.
Check that your unit selections (such as raidunit) are not set to none, i believe you should be setting it to something that you cannot recruit instead (such as a monk for an AI without a cathedral), again, this is not my area of expertise, so i could be wrong. I encourage you to ask on the discord server, as I know that those with your answer (assuming the problem is what i think it is) are quick to respond there.

**Comment by LeSpec** [comment]
Do you have a save file so i can explore the issue?
Units being not visible doesn't necessary mean they disappear, tunnelers for example. Recruiting the wrong type sometimes leads to invisibility too, e.g. recruiting jugglers.

**Comment by Euski** [comment]
I actually have Set Sorties to None, i'll try and See If ist helps. Otherwise i can Provide a save. Im not Shure If they go invisible, because the troop Count of the AI isnt raising when the Problem occures

**Comment by Euski** [comment]
Good Morning,

as far
